import React from "react";
import { Briefcase } from "lucide-react";

interface ExperienceProps {
  title: string;
  company: string;
  location: string;
  duration: string;
  bullets: string[];
  logo: string;
}

const experiences: ExperienceProps[] = [
  {
    title: "Data Analyst Intern",
    company: "Metropolitan Transportation Authority (MTA)",
    location: "New York, NY",
    duration: "January 2026 — Present",
    logo: "/images/mta.jpeg",
    bullets: [
      "Developed a Power Automate pipeline that iterated over 600+ Excel rows, matched records via PASS number lookup against a SharePoint list, and conditionally patched employee position and enrollment date fields to maintain accurate, up-to-date records across the Power Control department.",
      "Deployed an interactive Power BI dashboard with optimized DAX measures to visualize workforce distribution across 1,200+ Power Electrical and Third Rail employees and track 100+ accident trends, providing the General Superintendent with actionable safety insights.",
    ],
  },
  {
    title: "Software Engineer Fellow",
    company: "CUNY Tech Prep",
    location: "New York, NY",
    duration: "July 2025 — Present",
    logo: "/images/ctp.jpeg",
    bullets: [
      "Developed scalable web applications with React and TypeScript, boosting maintainability, optimizing performance, and enhancing user experience in collaborative, agile team projects.",
      "Integrated Node.js, Express.js, and PostgreSQL into full-stack applications while applying best practices in software architecture, version control, testing, and CI/CD to ensure reliable and production-ready deployments.",
      "Built a full-stack CUNY Hunter Marketplace utilizing Supabase and Prisma, implementing user authentication and an item listing dashboard for students to buy and sell college essentials.",
    ],
  },
  {
    title: "Software Engineer Intern",
    company: "Permanence AI",
    location: "New York, NY",
    duration: "January 2025",
    logo: "/images/permanence.jpeg",
    bullets: [
      "Analyzed ChatGPT's behavior by experimenting with key parameters, such as temperature and token limits, gaining a comprehensive understanding of AI model performance and response generation.",
      "Optimized prompt design to enhance the LLM's ability to generate accurate and relevant outputs with OpenAI API, leading to reduced token usage by ~15% and improved result quality to minimize additional queries.",
      "Engineered a Pythonic Code Evaluator to evaluate whether a user's code is Pythonic, enhancing code quality and optimizing multiple Python codebases generated by the LLM using Python and OpenAI API.",
    ],
  },
];

const ExperienceSection = () => {
  return (
    <section id="experience" className="py-24 relative overflow-hidden">
      <div className="absolute -top-20 -left-20 w-80 h-80 rounded-full bg-portfolio-cream/40 blur-3xl"></div>

      <div className="container relative">
        <div className="flex flex-col items-center text-center mb-16">
          <p className="section-eyebrow">— My Journey —</p>
          <h2 className="section-title">Experience</h2>
        </div>

        <div className="max-w-5xl mx-auto space-y-6">
          {experiences.map((exp, index) => (
            <div
              key={index}
              className="bg-gradient-to-br from-portfolio-cream to-portfolio-mauve/30 rounded-2xl p-5 md:p-6 border border-portfolio-mauve/20 shadow-md hover:shadow-2xl transition-all duration-500 hover:-translate-y-2"
            >
              <div className="flex items-start gap-4 mb-4">
                <img
                  src={exp.logo}
                  alt={exp.company}
                  className="w-12 h-12 object-contain rounded-lg border border-white/40 shadow-sm flex-shrink-0"
                />
                <div className="flex-1">
                  <h3 className="text-portfolio-navy text-xl font-bold">
                    {exp.title}
                  </h3>
                  <p className="text-portfolio-purple font-semibold mt-1">
                    {exp.company}
                  </p>
                  <p className="text-portfolio-navy/60 text-sm mt-1">
                    {exp.duration}
                  </p>
                </div>
              </div>
              <ul className="space-y-2">
                {exp.bullets.map((bullet, idx) => (
                  <li
                    key={idx}
                    className="flex items-start gap-2 text-portfolio-navy/70 text-sm leading-relaxed"
                  >
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-portfolio-purple flex-shrink-0"></span>
                    {bullet}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default ExperienceSection;
