import React from "react";

interface ExperienceProps {
  title: string;
  company: string;
  location: string;
  duration: string;
  bullets: string[];
  logo: string;
}

const experiences: ExperienceProps[] = [
  {
    title: "Data Analyst Intern",
    company: "Metropolitan Transportation Authority (MTA)",
    location: "New York, NY",
    duration: "January 2026 — Present",
    logo: "/images/mta.jpeg",
    bullets: [
      "Analyzed the MTA Power Cable Enterprise Asset Management database with 11,000+ manhole inspection records, using Python, Pandas, and NumPy to detect duplicate entries and drive a ∼15% increase in maintenance activity.",
      "Built and deployed an interactive Power BI dashboard with optimized DAX measures sourced from SharePoint to visualize personnel data across 1,200+ employees in electrical and third rail divisions, providing senior management with actionable operational insights.",
      "Developed an automated data pipeline using Excel Power Query and Power Automate to consolidate and sync 600+ employee records across SharePoint, reducing manual data entry and ensuring up-to-date workforce records.",
    ],
  },
  {
    title: "Software Engineer Fellow",
    company: "CUNY Tech Prep",
    location: "New York, NY",
    duration: "July 2025 — May 2026",
    logo: "/images/ctp.jpeg",
    bullets: [
      "Developed scalable web applications with React and TypeScript, boosting maintainability, optimizing performance, and enhancing user experience in collaborative, agile team projects.",
      "Integrated Node.js, Express.js, and PostgreSQL into full-stack applications while applying best practices in software architecture, version control, testing, and CI/CD to ensure reliable and production-ready deployments.",
      "Built a full-stack CUNY Hunter Marketplace utilizing Supabase and Prisma, implementing JWT-based user authentication and a dynamic item listing dashboard with CRUD functionality to enable student-to-student transactions.",
    ],
  },
  {
    title: "Software Engineer Intern",
    company: "Permanence AI",
    location: "New York, NY",
    duration: "January 2025",
    logo: "/images/permanence.jpeg",
    bullets: [
      "Examined ChatGPT’s response behavior through systematic temperature and token limit tuning, leveraging insights to engineer prompts that enhanced model performance and response generation.",
      "Optimized prompt design to enhance the LLM's ability to generate accurate and relevant outputs with OpenAI API, leading to reduced token usage by ~15% and improved result quality to minimize additional queries.",
      "Engineered a Pythonic Code Evaluator to evaluate whether a user's code is Pythonic, enhancing code quality and optimizing multiple Python codebases generated by the LLM using Python and OpenAI API.",
    ],
  },
  {
    title: "IT Service Management Intern",
    company: "New York City Housing Authority (NYCHA)",
    location: "New York, NY",
    duration: "July 2024 — August 2024",
    logo: "/images/nycha.png",
    bullets: [
      "Completed ServiceNow training in IT Service Management, with a focus on Knowledge Base and Incident Management to strengthen expertise in improving user experience and facilitating incident resolution.",
      "Reviewed 400+ Knowledge Base articles in ServiceNow, leading to actionable recommendations to keep, flag, review, or update its content.",
      "Conducted quality assurance by reviewing and validating 100+ Microsoft account requests from Movaris, ensuring accuracy on Microsoft Teams.",
      "Documented project charters and closing reports for key initiatives, recorded outcomes, and next steps with R-markdown to incorporate data visualization of our findings.",
    ],
  },
  {
    title: "Cybersecurity Intern",
    company: "The City of New York Office of Labor Relations",
    location: "New York, NY",
    duration: "July 2022 — August 2022",
    logo: "/images/nyc-olr.jpeg",
    bullets: [
      "Obtained a comprehensive understanding of cybersecurity by engaging in a panel led by the Center for Internet Security.",
      "Analyzed data from hardware and detected risk issues on PC through Linux commands.",
      "Handled IT Inventory Management by collecting 100+ PC and monitor tags, ensuring accurate asset tracking and organization.",
    ],
  },
];

const ExperienceSection = () => {
  return (
    <section id="experience" className="py-24 relative overflow-hidden">
      <div className="absolute -top-20 -left-20 w-80 h-80 rounded-full bg-portfolio-cream/40 blur-3xl"></div>

      <div className="container relative">
        <div className="flex flex-col items-center text-center mb-16">
          <p className="section-eyebrow">— My Journey —</p>
          <h2 className="section-title">Experience</h2>
        </div>

        <div className="max-w-5xl mx-auto space-y-6">
          {experiences.map((exp, index) => (
            <div
              key={index}
              className="bg-gradient-to-br from-portfolio-cream to-portfolio-mauve/30 rounded-2xl p-6 border border-portfolio-mauve/20 shadow-md hover:shadow-2xl transition-all duration-500 hover:-translate-y-2"
            >
              <div className="flex items-start gap-4 mb-4">
                <img
                  src={exp.logo}
                  alt={exp.company}
                  className="w-12 h-12 object-contain rounded-lg border border-white/40 shadow-sm flex-shrink-0"
                />
                <div className="flex-1">
                  <h3 className="text-portfolio-navy text-xl font-bold">
                    {exp.title}
                  </h3>
                  <p className="text-portfolio-purple font-semibold mt-1">
                    {exp.company}
                  </p>

                  {/* Tighter spacing: changed mx-2 to mx-1.5 and lowered opacity */}
                  <p className="text-portfolio-navy text-sm mt-1">
                    {exp.duration}
                    <span className="mx-1.5 opacity-100">·</span>
                    {exp.location}
                  </p>
                </div>
              </div>

              <ul className="space-y-2">
                {exp.bullets.map((bullet, idx) => (
                  <li
                    key={idx}
                    className="flex items-start gap-2 text-portfolio-navy text-sm leading-relaxed"
                  >
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-portfolio-purple flex-shrink-0"></span>
                    {bullet}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default ExperienceSection;
